# Generated by Django 3.1.3 on 2021-02-10 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('album_author', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorite', models.ManyToManyField(blank=True, related_name='album_favorite', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='album_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='art_img')),
                ('biography', models.TextField(null=True)),
                ('followers_fans', models.ManyToManyField(blank=True, related_name='followers_fans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomePagePlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inspired', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('playlist_img', models.ImageField(default='default.jpg', upload_to='playlist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inspired', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('playlist_img', models.ImageField(default='playlist_icon.jpg', upload_to='playlist_images')),
                ('favorite', models.ManyToManyField(blank=True, related_name='playlist_favorite', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='playlist_name', to=settings.AUTH_USER_MODEL)),
                ('playlist_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_author', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('category_color', models.CharField(max_length=200)),
                ('category_img', models.ImageField(default='category.jpg', upload_to='category_images')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('playlist_img', models.ImageField(default='playlist_icon.jpg', upload_to='user_playlist_images')),
                ('favorite', models.ManyToManyField(blank=True, related_name='user_playlist_favorite', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='user_playlist_name', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylists_songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_auther', models.CharField(max_length=200, null=True)),
                ('song_img', models.ImageField(upload_to='UserPlaylists_songs_images')),
                ('song_path', models.FileField(null=True, upload_to='UserPlaylists_songs_path')),
                ('lyrics', models.TextField(null=True)),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorite', models.ManyToManyField(blank=True, related_name='UserPlaylists_favorite_song', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='UserPlaylists_song_name', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userplaylists', to='main.userplaylists')),
            ],
        ),
        migrations.CreateModel(
            name='UserInheritedPlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userInheritedPlaylists', to='main.playlists')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userInherited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserArtists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userartist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_artist', to='main.artists')),
            ],
        ),
        migrations.CreateModel(
            name='Song_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_auther', models.CharField(max_length=200)),
                ('song_img', models.ImageField(upload_to='song_model_images')),
                ('song_path', models.FileField(upload_to='song_model_songs')),
                ('reference_name', models.CharField(max_length=200, null=True)),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('lyrics', models.TextField(null=True)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite_song', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='song_name', to=settings.AUTH_USER_MODEL)),
                ('song_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.song_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_auther', models.CharField(max_length=200)),
                ('song_img', models.ImageField(upload_to='song_images')),
                ('song_path', models.FileField(upload_to='playlist_songs')),
                ('reference_name', models.CharField(max_length=200, null=True)),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('lyrics', models.TextField(null=True)),
                ('favorite', models.ManyToManyField(blank=True, related_name='playlist_favorite_song', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='playlist_song_name', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='main.playlists')),
                ('song_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.song_categories')),
            ],
        ),
        migrations.CreateModel(
            name='HomePagePlaylists_songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_auther', models.CharField(max_length=200)),
                ('song_img', models.ImageField(upload_to='song_images')),
                ('song_path', models.FileField(upload_to='playlist_songs')),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=200, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_song_for_home', to='main.albums')),
                ('favorite', models.ManyToManyField(blank=True, related_name='home_page_playlist_favorite_song', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='home_page_playlist_song_name', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepageplaylist', to='main.homepageplaylists')),
            ],
        ),
        migrations.CreateModel(
            name='Album_songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_auther', models.CharField(max_length=200)),
                ('song_img', models.ImageField(upload_to='album_images')),
                ('song_path', models.FileField(upload_to='album_songs')),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=200, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='main.albums')),
                ('favorite', models.ManyToManyField(blank=True, related_name='album_favorite_song', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='album_song_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
