# Generated by Django 3.1.3 on 2021-02-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210210_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_model',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
