# Generated by Django 3.1.3 on 2021-02-16 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_homepageplaylists_songs_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverPage_UserInheritedPlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discover_userInheritedPlaylists', to='main.homepageplaylists')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discover_userInherited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
