# Generated by Django 3.1.3 on 2021-04-23 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_song_model_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choose_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
