# Generated by Django 3.1.3 on 2021-04-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210423_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_model',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_model', to='main.albums'),
        ),
    ]
