# Generated by Django 3.1.3 on 2021-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_model',
            name='song_authers',
            field=models.ManyToManyField(blank=True, related_name='song_authers', to='main.Artists'),
        ),
    ]
