# Generated by Django 3.1.3 on 2021-04-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_song_model_song_authers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song_model',
            old_name='song_auther',
            new_name='song_auther_written',
        ),
    ]
