# Generated by Django 3.1.3 on 2021-04-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210426_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='album_artist',
            field=models.ManyToManyField(blank=True, related_name='album_artist', to='main.Artists'),
        ),
    ]
