# Generated by Django 3.1.3 on 2021-05-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
    ]
