# Generated by Django 3.1.3 on 2021-05-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userfriends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['date_sent']},
        ),
    ]
