# Generated by Django 3.1.3 on 2021-05-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210510_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_sent']},
        ),
    ]
